import Header from "../../Components/Header";

import { FaRobot } from "react-icons/fa";

export default function Training() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-900 via-black to-gray-900">
      <Header />
      <main className="pt-24 pb-20 max-w-5xl mx-auto px-6 text-white">
        
        {/* Hero */}
        <div className="mb-12 text-center">
          <FaRobot className="w-20 h-20 mx-auto mb-4 text-blue-400" />
          <h1 className="text-5xl font-bold mb-4">Smart Training</h1>
          <p className="text-gray-300 text-lg max-w-3xl mx-auto">
            AI-powered workout plans designed to adapt to your progress and help you reach your fitness goals faster.
          </p>
        </div>

        {/* Features */}
        <section className="bg-gray-800 rounded-2xl p-8 mb-8">
          <h2 className="text-3xl font-bold mb-4">Key Features</h2>
          <ul className="list-disc list-inside text-gray-300 space-y-2">
            <li>Custom workout plans based on your goals</li>
            <li>Progress tracking and performance analytics</li>
            <li>Adaptive routines that evolve as you improve</li>
          </ul>
        </section>

        {/* Benefits */}
        <section className="bg-gray-800 rounded-2xl p-8 mb-8">
          <h2 className="text-3xl font-bold mb-4">Benefits</h2>
          <ul className="list-disc list-inside text-gray-300 space-y-2">
            <li>Maximize your strength and endurance</li>
            <li>Stay motivated with guided plans</li>
            <li>Safe and effective training for all levels</li>
          </ul>
        </section>

        {/* How it works */}
        <section className="bg-gray-800 rounded-2xl p-8 mb-8">
          <h2 className="text-3xl font-bold mb-4">How It Works</h2>
          <p className="text-gray-300 mb-2">
            1. Sign up and fill your fitness profile.
          </p>
          <p className="text-gray-300 mb-2">
            2. Receive a personalized workout plan generated by our AI system.
          </p>
          <p className="text-gray-300 mb-2">
            3. Track your progress and the plan automatically updates.
          </p>
          <p className="text-gray-300">
            4. Get real-time feedback and optimize your performance.
          </p>
        </section>
      </main>
    </div>
  );
}
